spring:
  # JPA configuration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performance
    username: devmind
    password: devmind
  resources:
    static-locations:
      - file:dm-client/build/dist/
  devtools:
    restart:
      additional-paths:
        - dm-client/build/dist/
      additional-exclude: "**/*.js, **/*.css, **/*.html, **/*.svg, **/*.png,, **/*.jpg"

server:
  ssl:
    key-store: classpath:perf.jks
    key-store-password: DevMind
    key-password: DevMind
    protocol: TLSv1.2
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
